name: build image

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**", "README.md", "Makefile", ".gitignore", ".pre-commit-config.yaml"]
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #----------------------------------------------
      # Prepare commit info for deploy
      #----------------------------------------------
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      #----------------------------------------------
      # Extact commit info for build
      #----------------------------------------------
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: "asapronov/${{ github.event.repository.name }}"
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
      #----------------------------------------------
      # Prepare for building image
      #----------------------------------------------
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      #----------------------------------------------
      # Auth to docker hub
      #----------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #----------------------------------------------
      # Build and upload image
      #----------------------------------------------
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          ulimit: nofile=1048576:1048576
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
